import type { LucideProps } from 'lucide-react'
import {
  Archive,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clipboard,
  Clock3,
  Copy,
  Download,
  ExternalLink,
  FileText,
  Folder,
  FolderOpen,
  Gauge,
  Highlighter,
  Image,
  Import,
  Languages,
  LayoutList,
  Lightbulb,
  ListFilter,
  Menu,
  MessageSquare,
  MoreHorizontal,
  PanelRight,
  Plus,
  RotateCcw,
  Save,
  Search,
  Settings2,
  Tag,
  Trash2,
  Type,
  Upload,
  WandSparkles,
  X,
} from 'lucide-react'

export const icons = {
  archive: Archive,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bookOpen: BookOpen,
  bookmark: Bookmark,
  bookmarkCheck: BookmarkCheck,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleHelp: CircleHelp,
  clipboard: Clipboard,
  clock: Clock3,
  copy: Copy,
  download: Download,
  externalLink: ExternalLink,
  fileText: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  gauge: Gauge,
  highlighter: Highlighter,
  image: Image,
  import: Import,
  languages: Languages,
  layoutList: LayoutList,
  lightbulb: Lightbulb,
  listFilter: ListFilter,
  menu: Menu,
  message: MessageSquare,
  more: MoreHorizontal,
  panelRight: PanelRight,
  plus: Plus,
  rotate: RotateCcw,
  save: Save,
  search: Search,
  settings: Settings2,
  tag: Tag,
  trash: Trash2,
  type: Type,
  upload: Upload,
  wand: WandSparkles,
  x: X,
} as const

export type IconName = keyof typeof icons

export function Icon({ name, size = 18, strokeWidth = 1.8, ...props }: { name: IconName; size?: number } & Omit<LucideProps, 'size'>) {
  const Component = icons[name]
  return <Component size={size} strokeWidth={strokeWidth} {...props} />
}
